<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_HMIWrapper" Id="{bd8d4674-e58e-47ef-b371-fe199b5f40ce}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_HMIWrapper
VAR
	Motion : FB_MotionDevices;
	HVPS: FB_HVPS;
	AirKnives : FB_BinaryDevice;
	VacuumRelay : FB_BinaryDevice;
	VacuumPurge : FB_BinaryDevice;
	Laser : FB_LaserDevice;
	Vision: FB_HMIVision;
	Zaber : FB_Zaber;
	// PLC : V3ToolPLC;
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="Cyclic" Id="{503900e1-7251-4db4-8d78-bfc87e868742}">
      <Declaration><![CDATA[METHOD Cyclic : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[HVPS.Cyclic();
Vision.Cyclic();
Motion.Cyclic();
AirKnives.Cyclic();
VacuumRelay.Cyclic();
VacuumPurge.Cyclic();
Laser.Cyclic();
Zaber.Cyclic();]]></ST>
      </Implementation>
    </Method>
    <Method Name="HandleCommands" Id="{6564dcd2-e724-4b2f-a668-432b1df95edd}">
      <Declaration><![CDATA[METHOD HandleCommands : BOOL
VAR_INPUT

END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="Init" Id="{a82e4cb6-dce8-446c-af1d-0fedfcfecce1}">
      <Declaration><![CDATA[METHOD Init : BOOL
VAR_INPUT
	refMotion : Motion.I_WebDrive;
	refHVPS: REFERENCE TO FB_HVPS_System;
	refAirKnives : Discrete.I_DiscreteBase;
	refVacuumRelay : Discrete.I_DiscreteBase;
	refVacuumPurge : Discrete.I_DiscreteBase;
	refLaser : Discrete.I_Laser;
	refVision: Vision.I_Vision;
	refZaberGroup : Motion.I_ZaberAxisGroup;
	// PLC : V3ToolPLC;
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[Motion.Init(refMotion);
HVPS.Init(refHVPS);
AirKnives.Init(refAirKnives);
VacuumRelay.Init(refVacuumRelay);
VacuumPurge.Init(refVacuumPurge);
Vision.Init(refVision);
Laser.Init(refLaser);
Zaber.Init(refZaberGroup);
]]></ST>
      </Implementation>
    </Method>
  </POU>
</TcPlcObject>