<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1">
  <POU Name="FB_RotaryEncoder" Id="{b03b6cc7-f3f4-4091-99dd-be277cfee204}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_RotaryEncoder EXTENDS FB_HMIBase
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
  </POU>
</TcPlcObject>